package com.efrei.uml.course;

public enum Topic {
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    DESKTOP_DEVELOPMENT,
    DEVOPS,
    CLOUD_COMPUTING,
    BIG_DATA,
    BIO_ENGINEERING,
    FRENCH_HISTORY,
    FRENCH_GEOGRAPHY, OBJECT_ORIENTED_PROGRAMMING,
}
